#meeting:    /var/tools/secretary/foundation/Meetings/20140527
:foundation: /var/tools/secretary/foundation
:officers:   /var/tools/secretary/foundation/officers
:documents:  /var/tools/secretary/documents
:received:   /var/tools/secretary/documents/received
:mail:       /var/tools/secretary/secmail.rb
:subreq:     /var/tools/secretary/subreq
:old_podlings:
  - 'allura'
  - 'ambari'
  - 'blur'
  - 'celix'
  - 'chukwa'
  - 'deltaspike'
  - 'devicemap'
  - 'drill'
  - 'droids'
  - 'hcatalog'
  - 'jspwiki'
  - 'kafka'
  - 'kalumet'
  - 'mesos'
  - 'npanday'
  - 'odf'
  - 'onami'
  - 's4'
  - 'tashi'
  - 'vxquery'
  - 'wave'
    
